name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures the full repo is checked out

      - name: Debug - List project files
        run: ls -l # Check if frontend folder exists

      - name: Debug - Show current directory
        run: pwd # Print current working directory

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build

